#!/bin/bash
# iterate through all the files in a directory
for file in /home/rich/test/*
do
if [ -d “$file” ]
then
www.it-ebooks.info
echo “$file is a directory”
elif [ -f “$file” ]
then
echo “$file is a file”
fi
done
